trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Janco International - Dev'
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.0.x'
  entityFrameworkVersion: '6.0.*'
  resourceGroup: 'tymr'
  webAppName: 'tymr-client'
  artifactPath: 'deploy-packages'

jobs:
- job: BuildAndPublish
  displayName: 'Build and Publish Artifacts'
  steps:

   # Build Client project
  - task: DotNetCoreCLI@2
    displayName: 'Build Client project - $(webAppName)'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Client'
      projects: 'Tymr.Client/Tymr.Client.csproj'

    # Zip Client Build Artifacts
  - task: PowerShell@2
    displayName: 'Create Zip Package for Client'
    inputs:
      targetType: 'inline'
      script: |
        $outputDirClient = "$(Build.ArtifactStagingDirectory)/Client"
        $zipPathClient = "$(Build.ArtifactStagingDirectory)/Tymr.Client.zip"
        Compress-Archive -Path $outputDirClient/* -DestinationPath $zipPathClient

    # Publish Client Build Artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Client Build Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Tymr.Client.zip'
      ArtifactName: 'deploy-packages'
      publishLocation: 'Container'

# Deploy Client

  - task: AzureWebApp@1
    displayName: 'Publish Client Build Artifacts'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webApp'
      appName: '$(webAppName)'
      package: '$(Pipeline.Workspace)/$(artifactPath)/Tymr.Client.zip'
      deploymentMethod: 'runFromPackage'