trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  
  - name: azureSubscription
    value: 'Janco International - Dev(67893773-5aef-487e-83db-5b6b89272593)'

  - name: buildConfiguration
    value: 'Release'

  - name: dotnetSdkVersion
    value: '6.0.x'

  - name: entityFrameworkVersion
    value: '6.0.*'

  - name: resourceGroup
    value: 'tymr'

  - name: webAppName
    value: 'tymr-client'

  - name: artifactPath
    value: 'deploy-packages'

steps:

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'

