trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Janco International - Dev'
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.0.x'
  entityFrameworkVersion: '6.0.*'
  resourceGroup: 'tymr'
  webAppName: 'tymr-client'
  artifactPath: 'Tymr/published'

jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy Application'
    steps:
      - checkout: self
      
      - task: UseDotNet@2
        displayName: 'Setup .NET SDK'
        inputs:
          version: $(dotnetSdkVersion)
          packageType: sdk

      # Restore NuGet packages
      - task: DotNetCoreCLI@2
        displayName: 'Restore NuGet packages'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'

      # Build Client project
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

      # Run tests
      - task: DotNetCoreCLI@2
        displayName: 'Test'
        inputs:
          command: 'test'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration) --no-build'

      # Publish Client Build Artifacts
      - task: DotNetCoreCLI@2
        displayName: 'Publish'
        inputs:
          command: 'publish'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(artifactPath) --no-build'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(artifactPath)'
          ArtifactName: 'webapp'
          publishLocation: 'Container'

      # Deploy Client
      - task: AzureWebApp@1
        displayName: 'Deploy to Azure WebApp'
        inputs:
          azureSubscription: $(azureSubscription)
          appName: $(webAppName)
          package: '$(Build.ArtifactStagingDirectory)/$(artifactPath)'
          deploymentMethod: 'runFromPackage'
