trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Janco International - Dev'
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.0.x'
  entityFrameworkVersion: '6.0.*'
  resourceGroup: 'tymr'
  webAppName: 'tymr-client'
  artifactPath: 'deploy-packages'

jobs:
- job: Build
  displayName: 'Build Application'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'Tymr.Client.csproj'
      arguments: '--no-restore --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Client'
