trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'Janco International - Dev'
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.0.x'
  webAppName: 'tymr-client'
  artifactPath: 'deploy-packages'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test Application'
  steps:
    - checkout: self
    
    - task: UseDotNet@2
      displayName: 'Setup .NET SDK'
      inputs:
        version: $(dotnetSdkVersion)
        packageType: sdk

    # Restore NuGet packages for all projects
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    # Build solution excluding test projects to avoid unnecessary builds
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'
        excludeProjects: '**/*Tests.csproj'

    # Run tests
    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --collect "Code coverage"'
        publishTestResults: true

    # Publish Build Artifacts
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    
    # Upload all the files in $(Build.ArtifactStagingDirectory) as an artifact of the build
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: '$(artifactPath)'

# Deploy Client to Azure Web App
- job: Deploy
  displayName: 'Deploy Application'
  dependsOn: BuildAndTest
  condition: succeeded()
  steps:
    - download: current
      artifact: '$(artifactPath)'
    - task: AzureWebApp@1
      displayName: 'Deploy Client to Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webApp'
        appName: $(webAppName)
        package: '$(Pipeline.Workspace)/$(artifactPath)/Tymr.zip'
