trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  
  - name: azureSubscription
    value: 'Janco International - Dev'

  - name: buildConfiguration
    value: 'Release'

  - name: dotnetSdkVersion
    value: '6.0.x'

  - name: entityFrameworkVersion
    value: '6.0.*'

  - name: resourceGroup
    value: 'tymr'

  - name: webAppName
    value: 'tymr-client'

  - name: artifactPath
    value: 'deploy-packages'

steps:

  # Build Client project
  - task: DotNetCoreCLI@2
    displayName: 'Build Client project - $(webAppName)'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Client'
      projects: 'Tymr.Client/Tymr.Client.csproj'


# Publish Client Build Artifacts
  # Zip
  - task: PowerShell@2
    displayName: 'Create Zip Package for Client'
    inputs:
      targetType: 'inline'
      script: |
        $outputDirClient = "$(Build.ArtifactStagingDirectory)/Client"
        $zipPathClient = "$(Build.ArtifactStagingDirectory)/Tymr.Client.zip"
        Compress-Archive -Path $outputDirClient/* -DestinationPath $zipPathClient

# Publish
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Client Build Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Tymr.Client.zip'
      ArtifactName: 'deploy-packages'
      publishLocation: 'Container'

# Deploy Client
jobs:
  - deployment: DeployClient
    displayName: Deploy Client
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(artifactPath)'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(azureSubscription)'
              RemoveAdditionalFilesFlag: true
              appType: 'webApp'
              WebAppName: '$(webAppName)'
              deployToSlotOrASE: false
              # SlotName: '${{ parameters.slot }}'
              ResourceGroupName: '$(resourceGroup)' 
              packageForLinux: '$(Pipeline.Workspace)/$(artifactPath)/Tymr.Client.zip'


# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '$(azureSubscription)'
#     appType: 'webApp'
#     appName: '$(webAppName)'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#     deploymentMethod: 'auto'

